// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIoElmKf4J5Uorp5sUCQ5d2rSt100p2l8',
    appId: '1:179684636288:web:cdc481a360a9b3a47dd865',
    messagingSenderId: '179684636288',
    projectId: 'flutterhomework-8dc5f',
    authDomain: 'flutterhomework-8dc5f.firebaseapp.com',
    databaseURL: 'https://flutterhomework-8dc5f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterhomework-8dc5f.firebasestorage.app',
    measurementId: 'G-PNPLML7WSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgwW6gEZnMV5re4gK3oNEfKTz7UqIMqc',
    appId: '1:179684636288:android:6e655594db8da8f87dd865',
    messagingSenderId: '179684636288',
    projectId: 'flutterhomework-8dc5f',
    databaseURL: 'https://flutterhomework-8dc5f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterhomework-8dc5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5f1jx99lnQisy93rNJBf9EvxxkFr5wYs',
    appId: '1:179684636288:ios:61442e15c6cd2c157dd865',
    messagingSenderId: '179684636288',
    projectId: 'flutterhomework-8dc5f',
    databaseURL: 'https://flutterhomework-8dc5f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterhomework-8dc5f.firebasestorage.app',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5f1jx99lnQisy93rNJBf9EvxxkFr5wYs',
    appId: '1:179684636288:ios:61442e15c6cd2c157dd865',
    messagingSenderId: '179684636288',
    projectId: 'flutterhomework-8dc5f',
    databaseURL: 'https://flutterhomework-8dc5f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterhomework-8dc5f.firebasestorage.app',
    iosBundleId: 'com.example.homework',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIoElmKf4J5Uorp5sUCQ5d2rSt100p2l8',
    appId: '1:179684636288:web:0b73d4e3555c9f9e7dd865',
    messagingSenderId: '179684636288',
    projectId: 'flutterhomework-8dc5f',
    authDomain: 'flutterhomework-8dc5f.firebaseapp.com',
    databaseURL: 'https://flutterhomework-8dc5f-default-rtdb.firebaseio.com',
    storageBucket: 'flutterhomework-8dc5f.firebasestorage.app',
    measurementId: 'G-PH4LL6F0BV',
  );

}