// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuR0CFpkojHVWKQ1at1bCPhQDhV75ZkSk',
    appId: '1:878763209324:web:376308c229cfef7b0dde49',
    messagingSenderId: '878763209324',
    projectId: 'lunarcinema-1f70e',
    authDomain: 'lunarcinema-1f70e.firebaseapp.com',
    storageBucket: 'lunarcinema-1f70e.firebasestorage.app',
    measurementId: 'G-47TW7EK6L4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPaJVar64-l1bBPWn5do3hIXcvd0BAs04',
    appId: '1:878763209324:android:8623f95270d8e2490dde49',
    messagingSenderId: '878763209324',
    projectId: 'lunarcinema-1f70e',
    storageBucket: 'lunarcinema-1f70e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpMozWxujWdxinSkRYR5c2I-w1V7mEO8A',
    appId: '1:878763209324:ios:07c87568a03b89570dde49',
    messagingSenderId: '878763209324',
    projectId: 'lunarcinema-1f70e',
    storageBucket: 'lunarcinema-1f70e.firebasestorage.app',
    iosBundleId: 'com.example.lunarCinema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpMozWxujWdxinSkRYR5c2I-w1V7mEO8A',
    appId: '1:878763209324:ios:07c87568a03b89570dde49',
    messagingSenderId: '878763209324',
    projectId: 'lunarcinema-1f70e',
    storageBucket: 'lunarcinema-1f70e.firebasestorage.app',
    iosBundleId: 'com.example.lunarCinema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuR0CFpkojHVWKQ1at1bCPhQDhV75ZkSk',
    appId: '1:878763209324:web:d3282bb584a923490dde49',
    messagingSenderId: '878763209324',
    projectId: 'lunarcinema-1f70e',
    authDomain: 'lunarcinema-1f70e.firebaseapp.com',
    storageBucket: 'lunarcinema-1f70e.firebasestorage.app',
    measurementId: 'G-VQTP8F17VC',
  );

}